// Generated by gencpp from file object_msgs/RegisterObjectResponse.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_REGISTEROBJECTRESPONSE_H
#define OBJECT_MSGS_MESSAGE_REGISTEROBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_msgs
{
template <class ContainerAllocator>
struct RegisterObjectResponse_
{
  typedef RegisterObjectResponse_<ContainerAllocator> Type;

  RegisterObjectResponse_()
    : success(0)  {
    }
  RegisterObjectResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef int8_t _success_type;
  _success_type success;



  enum {
    SUCCESS = 0,
    EXISTS = 1,
    ERROR_INFO = 2,
  };


  typedef boost::shared_ptr< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterObjectResponse_

typedef ::object_msgs::RegisterObjectResponse_<std::allocator<void> > RegisterObjectResponse;

typedef boost::shared_ptr< ::object_msgs::RegisterObjectResponse > RegisterObjectResponsePtr;
typedef boost::shared_ptr< ::object_msgs::RegisterObjectResponse const> RegisterObjectResponseConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::RegisterObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'object_msgs': ['/home/student/catkin_ws/src/general-message-pkgs/object_msgs/msg'], 'shape_msgs': ['/opt/ros/melodic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/melodic/share/object_recognition_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9c25147bff223b8f5fb48665bb7c161";
  }

  static const char* value(const ::object_msgs::RegisterObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9c25147bff223b8ULL;
  static const uint64_t static_value2 = 0xf5fb48665bb7c161ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/RegisterObjectResponse";
  }

  static const char* value(const ::object_msgs::RegisterObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"byte success\n"
"\n"
"\n"
"byte SUCCESS=0\n"
"\n"
"\n"
"byte EXISTS=1\n"
"\n"
"\n"
"byte ERROR_INFO=2\n"
"\n"
;
  }

  static const char* value(const ::object_msgs::RegisterObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::RegisterObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::RegisterObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_REGISTEROBJECTRESPONSE_H
